// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DynamicComponents: typeof import('./src/components/DynamicComponents.vue')['default']
    Error: typeof import('./src/components/Error.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    PropsAndEmit: typeof import('./src/components/PropsAndEmit.vue')['default']
    Reactivity: typeof import('./src/components/Reactivity.vue')['default']
    SlotsAndAttrs: typeof import('./src/components/SlotsAndAttrs.vue')['default']
    SystemMenu: typeof import('./src/components/SystemMenu.vue')['default']
  }
}

export { }
