// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATable: typeof import('ant-design-vue/es')['Table']
    DynamicComponents: typeof import('./components/DynamicComponents.vue')['default']
    Error: typeof import('./components/Error.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Loading: typeof import('./components/Loading.vue')['default']
    Markdown: typeof import('./components/Markdown.vue')['default']
    PropsAndEmit: typeof import('./components/PropsAndEmit.vue')['default']
    Reactivity: typeof import('./components/Reactivity.vue')['default']
    SlotsAndAttrs: typeof import('./components/SlotsAndAttrs.vue')['default']
    StoryLayout: typeof import('./components/StoryLayout.vue')['default']
  }
}

export { }
