// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DynamicComponents: typeof import('./components/DynamicComponents.vue')['default']
    Error: typeof import('./components/Error.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Loading: typeof import('./components/Loading.vue')['default']
    Markdown: typeof import('./components/Markdown.vue')['default']
    PropsAndEmit: typeof import('./components/PropsAndEmit.vue')['default']
    Reactivity: typeof import('./components/Reactivity.vue')['default']
    SlotsAndAttrs: typeof import('./components/SlotsAndAttrs.vue')['default']
    StoryLayout: typeof import('./components/StoryLayout.vue')['default']
  }
}

export { }
